-- CreateEnum
CREATE TYPE "ContentType" AS ENUM (
  'YOUTUBE_VIDEO',
  'YOUTUBE_SHORT',
  'INSTAGRAM_REEL',
  'TIKTOK_SHORT',
  'PODCAST_EPISODE',
  'PODCAST_CLIP',
  'AUDIO_AD',
  'LIVE_STREAM',
  'WEBINAR',
  'COURSE_LESSON',
  'LECTURE_RECORDING',
  'AD_CREATIVE',
  'PRODUCT_DEMO'
);

-- AlterTable
ALTER TABLE "Analysis"
ADD COLUMN "contentType" "ContentType" NOT NULL DEFAULT 'YOUTUBE_VIDEO';
