export enum Plan {
  FREE = 'FREE',
  CREATOR = 'CREATOR',
  PRO = 'PRO'
}

export enum SourceType {
  FILE = 'FILE',
  YOUTUBE_URL = 'YOUTUBE_URL'
}

export enum ContentType {
  YOUTUBE_VIDEO = 'YOUTUBE_VIDEO',
  YOUTUBE_SHORT = 'YOUTUBE_SHORT',
  INSTAGRAM_REEL = 'INSTAGRAM_REEL',
  TIKTOK_SHORT = 'TIKTOK_SHORT',
  PODCAST_EPISODE = 'PODCAST_EPISODE',
  PODCAST_CLIP = 'PODCAST_CLIP',
  AUDIO_AD = 'AUDIO_AD',
  LIVE_STREAM = 'LIVE_STREAM',
  WEBINAR = 'WEBINAR',
  COURSE_LESSON = 'COURSE_LESSON',
  LECTURE_RECORDING = 'LECTURE_RECORDING',
  AD_CREATIVE = 'AD_CREATIVE',
  PRODUCT_DEMO = 'PRODUCT_DEMO'
}

export enum AnalysisStatus {
  QUEUED = 'QUEUED',
  DOWNLOADING = 'DOWNLOADING',
  EXTRACTING_FEATURES = 'EXTRACTING_FEATURES',
  RUNNING_TRIBE = 'RUNNING_TRIBE',
  SCORING = 'SCORING',
  GENERATING_INSIGHTS = 'GENERATING_INSIGHTS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum Grade {
  A = 'A',
  B = 'B',
  C = 'C',
  D = 'D'
}

export enum FormatType {
  SHORT_FORM = 'SHORT_FORM',
  STANDARD = 'STANDARD',
  LONG_FORM = 'LONG_FORM'
}

export enum InsightType {
  BOREDOM_SPIKE = 'BOREDOM_SPIKE',
  EMOTION_PEAK = 'EMOTION_PEAK',
  HOOK_MOMENT = 'HOOK_MOMENT',
  CRITICAL_DROP = 'CRITICAL_DROP'
}

export enum InsightSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}
